baseURL = 'https://seu-usuario.github.io/salvo-engano/'
languageCode = 'pt-br'
title = 'Salvo Engano'
theme = 'hugo-theme-relearn'

[params]
  description = 'Meu blog pessoal criado com Hugo e o tema Relearn'
  author = 'Seu Nome'
  
[params.relearnVariant]
  themeVariant = 'zen-light'
  
[params.relearnTheme]
  themeAuto = true
  
[languages]
  [languages.pt-br]
    languageName = 'Português'
    languageCode = 'pt-br'
    weight = 1
